name: release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  binaries:
    name: binaries
    runs-on: macos-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Install gox
        run: go install github.com/mitchellh/gox@master

      - name: Build release (windows and linux)
        run: >
          gox -output="{{.OS}}/{{.Arch}}/{{.Dir}}" \
            -osarch='windows/amd64 linux/amd64' -ldflags="
            -X 'github.com/gorse-io/gorse/cmd/version.Version=$(git describe --tags $(git rev-parse HEAD))'
            -X 'github.com/gorse-io/gorse/cmd/version.GitCommit=$(git rev-parse HEAD)'
            -X 'github.com/gorse-io/gorse/cmd/version.BuildTime=$(date)'" ./...
        env:
          CGO_ENABLED: 0

      - name: Install zip
        run: brew install zip

      - name: Zip binaries
        run: |
          zip -j gorse_linux_amd64.zip linux/amd64/gorse-*
          zip -j gorse_windows_amd64.zip windows/amd64/gorse-*

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: gorse_*_*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
